
tasks:
  - id: 'task_read_file'
    type: 'ReadFileTask'
    inputs:
      file_path: 'examples/summaryze/input.txt'
    outputs:
      content: 'summarize_text.argument1'

  - id: 'summarize_text'
    type: 'AskAi'
    inputs:
      prompt: 'Summarize the following text: {{argument1}}'
    outputs:
      response:
        - 'generate_file_name.argument1'
        - 'write_summary.content'

  - id: 'generate_file_name'
    type: 'AskAi'
    inputs:
      prompt: 'Generate the appropriate filename and extension for this content, do not include any explanation: {{argument1}}'
    outputs:
      response:
          - 'write_summary.path'

  - id: 'write_summary'
    type: 'WriteFileTask'
